version: '2'
services:
  portfolio:
    build: https://github.com/pcorderoe/espejozen-portfolio.git
    container_name: portfolio
    environment:
      - VIRTUAL_HOST=beta.espejozen.cl
      - LETSENCRYPT_HOST=beta.espejozen.cl
    network_mode: bridge
